### ISSUE TITLE
Gradle setup works only with 5.x

### ISSUE THREAD

**Issue by pankajagrawal16** [awslabs/aws-lambda-powertools-java#146]
**More details to be added **

**What were you trying to accomplish?**

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Environment

* **Powertools version used**:
* **Packaging format (Layers, Maven/Gradle)**:
* **AWS Lambda function runtime:**
* **Debugging logs**

> [How to enable debug mode](https://awslabs.github.io/aws-lambda-powertools-java/#debug-mode)**

```text
# paste logs here
```

**Comment by pankajagrawal16** [comment]
Latest version [0.0.6](https://plugins.gradle.org/plugin/aspectj.AspectjGradlePlugin/0.0.6) of AspectjGradlePlugin works with Java 11 and Gradle 6.x.

Unfortunately it wont be supported for Java 8 since java 11 is the current LTS version. Ref [issue](https://github.com/arendd/AspectjGradlePlugin/issues/7)

**Comment by michaelbrewer** [comment]
And it does not work at all with Gradle 7+

**Comment by pankajagrawal16** [comment]
> And it does not work at all with Gradle 7+

Yeah I need to dive a bit deeper into this and see how we can get it to work with gradle 7+

**Comment by pankajagrawal16** [comment]
All gradle 5 and 6 related issues should now be fixed with using latest version of AspectGradlePlugin with version 0.0.7 https://github.com/awslabs/aws-lambda-powertools-java/releases/tag/v1.9.0

**Comment by michaelbrewer** [comment]
@pankajagrawal16 still not working for me? Could we try https://docs.freefair.io/gradle-plugins/5.0.1/reference/#_aspectj instead?

**Comment by pankajagrawal16** [comment]
> @pankajagrawal16 still not working for me? Could we try https://docs.freefair.io/gradle-plugins/5.0.1/reference/#_aspectj instead?

Hey, this is the plugin which I was going to look into, but i am not working this week, so will check once back.

**Comment by michaelbrewer** [comment]
@pankajagrawal16 @msailes - i have created a PR to potentially fix the gradle plugin used for AspectJ

- https://github.com/arendd/AspectjGradlePlugin/pull/9

**Comment by pankajagrawal16** [comment]
@michaelbrewer It works with freefair gradle plugin. I have validated it and change is pretty simple. Would you mind validating it as well ? I am thinking we can officially update our docs to used free fair instead coz it seems to be actively maintained and works on gradle 5,6 and 7 as well

**Comment by pankajagrawal16** [comment]
This is what my sample build.gradle looks like for a sample hellp world gradle app via 

`sam init --location gh:aws-samples/cookiecutter-aws-sam-powertools-java`

```
plugins{
    id 'java'
//    id 'aspectj.AspectjGradlePlugin' version '0.0.7'
    id "io.freefair.aspectj.post-compile-weaving" version "5.0.1"
}

repositories {
    mavenCentral()
}

aspectj {
    version  = "1.9.7"
}

dependencies {
    aspect "software.amazon.lambda:powertools-logging:1.10.0"
    aspect 'software.amazon.lambda:powertools-tracing:1.10.0'
    aspect 'software.amazon.lambda:powertools-metrics:1.10.0'

    implementation 'com.amazonaws:aws-lambda-java-core:1.2.1'
    implementation 'com.amazonaws:aws-lambda-java-events:3.11.0'

    implementation 'org.apache.logging.log4j:log4j-api:2.17.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.17.0'

    testImplementation 'junit:junit:4.13.2'
}
```

**Comment by pankajagrawal16** [comment]
Docs and cookiecutter projects are now update to use the new config which should work for all gradle versions 5, 6 and 7.

cc @michaelbrewer Closing this now, Let me know if you face any issues.

**Comment by michaelbrewer** [comment]
@pankajagrawal16 - FYI my  PR for [aspectj.AspectjGradlePlugin](https://github.com/arendd/AspectjGradlePlugin/pull/9) was merged

**Comment by pankajagrawal16** [comment]
woho.. nice.. then probably we have two ways of configuring gradle project. I am still in favor of keeping freefair now since its much more active.

**Comment by michaelbrewer** [comment]
Yep, i agree, when i tried freefair initially i could not verify locally it was working (only when deployed)
